import PageBody from "@/components/layouts/page/page-body";
import PageMainHeader from "@/components/layouts/page/page-main-header";

export default function CVPage() {
    return <>
        <PageMainHeader>CV</PageMainHeader>
        <PageBody>
            Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Curabitur blandit quis mauris tincidunt iaculis. Aliquam elementum vestibulum interdum. Donec eu viverra ante, vitae pulvinar mauris. Vestibulum sed ante a felis posuere porta. Sed vel rhoncus magna. Nunc feugiat ante ut leo feugiat, nec malesuada leo accumsan. Integer eget mattis eros, et iaculis elit. Nam nibh justo, vestibulum eget nisi vel, aliquam feugiat nulla. Vestibulum vel justo risus. Praesent enim purus, venenatis efficitur fermentum eu, tempus id magna. Vivamus nec tellus ac risus posuere ornare quis id eros. Morbi vitae urna odio.
            Pellentesque justo purus, pretium sed scelerisque eget, scelerisque nec nisi. Morbi venenatis in sapien ut ultricies. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer elit dolor, mollis et nisi eget, volutpat gravida nunc. Nam pulvinar arcu vitae dolor laoreet laoreet. Proin ultricies dignissim nisi eget efficitur. In a faucibus massa. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Nulla sit amet rutrum nibh. Donec arcu sapien, facilisis eget ipsum sed, vestibulum bibendum felis. Proin vel nisl tortor. Suspendisse tincidunt tincidunt enim et dignissim. Aenean accumsan malesuada congue. Suspendisse maximus ornare nisi sit amet iaculis.
            Maecenas vitae pellentesque lectus. Nullam arcu quam, faucibus ut urna eu, varius fermentum dui. Nullam quis ipsum vel enim cursus condimentum. Aenean pulvinar, enim ac tincidunt hendrerit, massa lorem varius turpis, eget vestibulum velit urna eu arcu. Donec volutpat ornare sapien sed consequat. Vestibulum et libero diam. Curabitur eget dolor placerat massa sodales laoreet.
            Praesent eu hendrerit eros, non malesuada nunc. Cras malesuada erat vitae tellus tincidunt, sit amet tempor mauris molestie. Quisque id enim urna. Nullam condimentum tellus nulla, in ultrices ipsum ornare non. Pellentesque eget facilisis augue. Phasellus vestibulum odio non lacinia imperdiet. Vivamus justo tellus, consequat eu euismod quis, vestibulum nec nulla. Maecenas vestibulum elit eu est mollis condimentum. Morbi erat erat, euismod sit amet lobortis sed, vulputate non nisl. Fusce ut sodales ex. Cras a ex vel ex malesuada dignissim vel ac nulla. Suspendisse massa nisi, sagittis at egestas at, tempor eu lectus. Phasellus gravida in erat vel consectetur. Quisque nec erat dictum, consectetur tortor at, porttitor tellus. Phasellus elit arcu, cursus et ultrices vitae, pharetra non orci.
            Maecenas eleifend lectus ac neque semper interdum vitae eu diam. Pellentesque felis erat, aliquam ut erat nec, porttitor varius sapien. Duis sapien turpis, hendrerit vel magna vitae, eleifend tempus sapien. Maecenas vel cursus massa. In consectetur nisl dictum eros feugiat venenatis in et urna. Duis tincidunt suscipit quam congue commodo. Morbi rutrum viverra dolor at aliquet. Vestibulum vel eleifend nisi, ac aliquet neque. Nullam vel risus arcu. Donec fringilla tincidunt iaculis. Donec ut sagittis nulla, fringilla fermentum enim.
        </PageBody>
    </>
}