import PageBody from "@/components/layouts/page/page-body";
import PageMainHeader from "@/components/layouts/page/page-main-header";

export default function Home() {
  return <>
    <PageMainHeader>
      JPX
    </PageMainHeader>
    <PageBody>
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras scelerisque odio quis massa posuere pellentesque. Pellentesque sed dui dictum, venenatis elit eget, scelerisque libero. Aenean egestas molestie lacus, nec imperdiet turpis gravida id. Curabitur tincidunt semper blandit. Vivamus bibendum augue at dolor varius posuere. Sed dolor felis, vulputate quis aliquam at, imperdiet non libero. Quisque ac lobortis sapien. Vivamus vel condimentum ex, at sodales mi. In placerat vel lectus in vestibulum. Mauris in feugiat est. Nullam fringilla turpis nulla, ut tempus erat egestas id. Donec luctus venenatis ultrices. Proin et ligula hendrerit, interdum nunc ac, iaculis neque. Cras in finibus quam, in posuere lorem.
      Praesent facilisis consectetur dolor, at finibus mi auctor vitae. Sed eleifend varius tellus, porta aliquet tortor venenatis nec. Nam sit amet semper nulla, eget ornare ex. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut aliquet nibh in erat aliquam luctus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum dapibus sapien sapien, in fermentum magna volutpat non. Aenean lacinia nunc non tellus venenatis porttitor. Nulla eleifend mattis quam, nec vestibulum orci efficitur at. Nullam eget justo eget orci faucibus vehicula quis vel massa. Pellentesque in felis porttitor, blandit mauris eu, cursus leo. Donec ultricies gravida arcu ut vehicula. Morbi porttitor urna vitae sollicitudin bibendum. Quisque vulputate ligula est, non pellentesque metus commodo quis. Praesent nec dui vel elit volutpat ultricies eu vel est. Vestibulum et placerat nisl, sed mollis leo.
      Aenean egestas nec felis at pharetra. Pellentesque molestie gravida nulla id lacinia. Curabitur nec odio at ex eleifend varius. Mauris nec leo elit. Suspendisse eu tristique quam. Nulla facilisi. Nam posuere dictum ipsum.
      Vestibulum sit amet dapibus magna, quis porta elit. Nunc at odio nec arcu efficitur interdum. Quisque eu ultricies magna. Suspendisse eu commodo ante, vitae consequat diam. Donec ut molestie odio. In hac habitasse platea dictumst. Sed efficitur, ex et lacinia aliquam, lectus tortor sodales tortor, eu tempor lectus justo eu est. Integer sit amet nibh finibus, consectetur magna eget, imperdiet nisi.
      Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Integer congue, turpis eu laoreet dapibus, nibh odio porttitor metus, et efficitur massa justo sit amet justo. Aenean vitae turpis sollicitudin, viverra dui non, congue velit. Suspendisse semper laoreet mi, vel egestas ipsum lacinia ac. Maecenas suscipit justo quis feugiat semper. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Curabitur ac tellus at magna sollicitudin sagittis nec ut dui. Ut mollis, lectus ut sollicitudin eleifend, est turpis gravida justo, in blandit arcu odio a augue. Proin mattis, nisi eget euismod condimentum, turpis nibh tempor ligula, at finibus enim massa sed nulla.
      <br /><br />
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras scelerisque odio quis massa posuere pellentesque. Pellentesque sed dui dictum, venenatis elit eget, scelerisque libero. Aenean egestas molestie lacus, nec imperdiet turpis gravida id. Curabitur tincidunt semper blandit. Vivamus bibendum augue at dolor varius posuere. Sed dolor felis, vulputate quis aliquam at, imperdiet non libero. Quisque ac lobortis sapien. Vivamus vel condimentum ex, at sodales mi. In placerat vel lectus in vestibulum. Mauris in feugiat est. Nullam fringilla turpis nulla, ut tempus erat egestas id. Donec luctus venenatis ultrices. Proin et ligula hendrerit, interdum nunc ac, iaculis neque. Cras in finibus quam, in posuere lorem.
      Praesent facilisis consectetur dolor, at finibus mi auctor vitae. Sed eleifend varius tellus, porta aliquet tortor venenatis nec. Nam sit amet semper nulla, eget ornare ex. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut aliquet nibh in erat aliquam luctus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum dapibus sapien sapien, in fermentum magna volutpat non. Aenean lacinia nunc non tellus venenatis porttitor. Nulla eleifend mattis quam, nec vestibulum orci efficitur at. Nullam eget justo eget orci faucibus vehicula quis vel massa. Pellentesque in felis porttitor, blandit mauris eu, cursus leo. Donec ultricies gravida arcu ut vehicula. Morbi porttitor urna vitae sollicitudin bibendum. Quisque vulputate ligula est, non pellentesque metus commodo quis. Praesent nec dui vel elit volutpat ultricies eu vel est. Vestibulum et placerat nisl, sed mollis leo.
      Aenean egestas nec felis at pharetra. Pellentesque molestie gravida nulla id lacinia. Curabitur nec odio at ex eleifend varius. Mauris nec leo elit. Suspendisse eu tristique quam. Nulla facilisi. Nam posuere dictum ipsum.
      Vestibulum sit amet dapibus magna, quis porta elit. Nunc at odio nec arcu efficitur interdum. Quisque eu ultricies magna. Suspendisse eu commodo ante, vitae consequat diam. Donec ut molestie odio. In hac habitasse platea dictumst. Sed efficitur, ex et lacinia aliquam, lectus tortor sodales tortor, eu tempor lectus justo eu est. Integer sit amet nibh finibus, consectetur magna eget, imperdiet nisi.
      Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Integer congue, turpis eu laoreet dapibus, nibh odio porttitor metus, et efficitur massa justo sit amet justo. Aenean vitae turpis sollicitudin, viverra dui non, congue velit. Suspendisse semper laoreet mi, vel egestas ipsum lacinia ac. Maecenas suscipit justo quis feugiat semper. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Curabitur ac tellus at magna sollicitudin sagittis nec ut dui. Ut mollis, lectus ut sollicitudin eleifend, est turpis gravida justo, in blandit arcu odio a augue. Proin mattis, nisi eget euismod condimentum, turpis nibh tempor ligula, at finibus enim massa sed nulla.
    </PageBody>
  </>
}
