import PageBody from "@/components/layouts/page/page-body";
import PageMainHeader from "@/components/layouts/page/page-header";

export default function MusicPage() {
    return <>
        <PageMainHeader>Music</PageMainHeader>
        <PageBody>
            Praesent sagittis euismod magna, ac auctor nibh laoreet in. Curabitur ut augue tortor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin consequat non justo quis gravida. Integer pharetra, ipsum vitae feugiat lobortis, mi lorem lacinia lorem, eget tincidunt tortor nibh quis dui. Nullam a porttitor leo, sit amet consequat orci. Proin elementum ex imperdiet felis dignissim, eu egestas sem laoreet. Mauris hendrerit justo in mi consectetur, a faucibus magna tincidunt. Pellentesque id posuere ante. Sed enim nulla, sagittis eget lorem sit amet, semper pulvinar dolor. Ut imperdiet justo sed tellus tempus, quis posuere mi ullamcorper. Donec imperdiet tempus turpis, et tincidunt diam lacinia at. Fusce consequat hendrerit nisl quis maximus.
            Morbi venenatis pretium ex in tincidunt. Integer id pharetra magna, in interdum mauris. Etiam sem mauris, tempor quis malesuada eu, commodo quis elit. Donec sagittis massa nulla, sit amet molestie dui consectetur ut. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Quisque porta vehicula turpis, in vehicula ante imperdiet vel. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Interdum et malesuada fames ac ante ipsum primis in faucibus. Cras hendrerit nisi vel ipsum accumsan mattis. Vestibulum malesuada nunc at dui porttitor auctor. Duis tortor dolor, vulputate eget metus nec, viverra porta dui. Praesent id ipsum eleifend velit pulvinar mattis. Donec quis velit ac sem fringilla condimentum id pellentesque felis. Donec venenatis elit quis velit dignissim euismod. Quisque feugiat ultrices ex, consectetur dignissim massa pretium eu. Vivamus nec egestas nisl, sed fringilla lacus.
            Mauris nec imperdiet ante, quis consequat massa. Etiam venenatis et nibh et placerat. Cras in lobortis sem. Praesent tempor felis lorem, ac vehicula est feugiat non. Integer porttitor dapibus turpis sed sodales. Etiam auctor quis lectus sit amet tempor. Aliquam erat volutpat. Quisque ultricies urna non sodales eleifend. Suspendisse pulvinar posuere accumsan. Suspendisse potenti. Praesent dignissim, sem sit amet commodo luctus, erat leo lobortis orci, at fringilla risus mauris ac quam. Etiam sodales sit amet sem vel sodales. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.
            Ut eget risus diam. Aenean scelerisque, ligula id tempor mollis, massa lectus aliquet orci, vel consectetur mi mi quis enim. Donec ac mauris quis sapien porttitor pulvinar non in diam. Integer nec purus congue, tincidunt massa ut, rutrum augue. Praesent vel nisl sit amet leo egestas venenatis. Quisque fringilla tempor mattis. Duis porta congue velit, sed eleifend est pretium in. Curabitur leo nulla, rutrum in tellus ac, vestibulum gravida nisl. Cras et eros tincidunt, euismod elit vel, fermentum massa. Sed non finibus augue. Morbi laoreet, nunc in ullamcorper pulvinar, turpis lorem vestibulum mi, sed gravida leo nisl quis mauris. Integer eu iaculis libero. Sed ex purus, dictum vel ipsum id, lacinia condimentum purus. Nunc tincidunt dignissim nisi, sed venenatis sem feugiat ac. Vivamus gravida iaculis lectus, ac eleifend mauris tempus vel. Suspendisse pretium consequat lacus sit amet facilisis.
            Nam sollicitudin consectetur elementum. Nullam vel magna imperdiet, pulvinar est sit amet, ultrices nibh. Vivamus placerat lectus et nibh rutrum imperdiet. Suspendisse tempus nec elit non ullamcorper. Integer tincidunt ex et nunc euismod, sit amet dictum est blandit. Aenean fermentum nunc ipsum, nec dignissim dolor ornare ut. Etiam vel ullamcorper dolor. Donec at ante at tortor auctor placerat. Quisque vel lorem non risus convallis tristique id id lectus. Duis ac ullamcorper massa.
        </PageBody>
    </>
}