import PageBody from "@/components/layouts/page/page-body"
import PageMainHeader from "@/components/layouts/page/page-header"

export default function AIPage() {
    return <>
        <PageMainHeader>Gen A.I.</PageMainHeader>
        <PageBody>
            Fusce at augue mauris. Integer quis arcu arcu. Morbi vehicula, enim eget porttitor semper, elit risus fermentum odio, sed convallis felis ante vitae arcu. Donec nulla lacus, pellentesque id ullamcorper nec, venenatis eget massa. Integer in enim sit amet mauris scelerisque sollicitudin. Praesent quis imperdiet ligula, ac rutrum sem. Integer eu purus pellentesque, tincidunt sapien nec, rutrum lacus. Aenean tristique iaculis tellus. Phasellus luctus, quam ac sodales sodales, erat tortor ultricies risus, et ultrices eros velit vel diam. Cras elementum tincidunt bibendum.
            Sed fermentum mauris eget arcu aliquet imperdiet. Proin at dictum nibh. Donec ornare mollis purus id porttitor. Suspendisse scelerisque tortor neque, eget gravida nunc ornare vel. Pellentesque ac nulla elementum, iaculis mauris eget, posuere dui. In eleifend blandit faucibus. Proin non justo quis erat pretium laoreet. Duis mattis, dolor vel iaculis tristique, magna odio lacinia est, ac dictum massa ligula vitae odio. Vestibulum posuere finibus efficitur. Duis porta ac arcu eget imperdiet. Aliquam ac velit sit amet augue tincidunt consectetur ut quis orci. Maecenas dictum nisl et sodales sollicitudin. Vivamus in finibus arcu. Praesent vel placerat elit.
            Integer lorem velit, ullamcorper non massa non, luctus gravida ex. Vestibulum eu hendrerit risus. Nulla eget quam blandit massa eleifend luctus. Donec tincidunt lorem leo, id malesuada mauris aliquam in. Aliquam ac aliquet nisl. Proin sodales magna eget lectus dapibus, ut tincidunt augue aliquam. Fusce non est erat. Cras quam ex, vehicula non pretium sed, convallis nec quam. Quisque tincidunt, quam vitae posuere commodo, mi massa venenatis lacus, eget sagittis dolor sapien eget ipsum. Integer convallis facilisis enim, sit amet aliquet lectus ornare id.
            Cras non urna interdum, dapibus augue nec, maximus eros. Fusce magna leo, egestas sed eleifend in, facilisis eu enim. Duis volutpat dictum commodo. Aenean feugiat ornare lorem, eget fringilla ligula faucibus in. Vivamus nec ligula eget ex pellentesque bibendum. Donec gravida tellus nec volutpat tempor. Aenean vitae elementum orci, sed malesuada mi. Etiam tempus, sapien a placerat blandit, massa neque aliquet nibh, sit amet bibendum nisi orci finibus est. Aliquam erat volutpat. Donec tristique cursus est non dictum. Suspendisse consectetur ultrices nunc sit amet scelerisque. Nam id convallis risus, non convallis elit. Nulla aliquet, odio at ultrices dapibus, neque orci aliquam est, eu posuere arcu ligula eget ex. Praesent a sapien ac enim sollicitudin elementum rhoncus nec risus. Nam varius turpis id nulla sagittis mollis.
            Sed sit amet ante eu dolor consequat consequat. Donec mollis aliquam elit eu fermentum. Curabitur blandit dolor est, sed venenatis erat tincidunt vitae. Pellentesque quis nisi sollicitudin, facilisis ex vel, pulvinar sem. Phasellus finibus sodales tellus eu porta. In cursus sodales nulla id iaculis. Ut eu ornare augue, vitae ornare nunc. Suspendisse tortor ante, laoreet quis lacinia sed, accumsan quis lorem. Cras est dolor, placerat et ante at, rhoncus ultricies lectus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed mattis erat quis erat varius, a consectetur enim tempor. Integer gravida leo orci, eu imperdiet urna ornare nec. Curabitur tempor urna at lectus pellentesque facilisis.
        </PageBody>
    </>
}